// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: buddygym/v1/checkin.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckinStatus int32

const (
	CheckinStatus_CHECKIN_STATUS_UNSPECIFIED CheckinStatus = 0
	CheckinStatus_CHECKIN_STATUS_PENDING     CheckinStatus = 1
	CheckinStatus_CHECKIN_STATUS_APPROVED    CheckinStatus = 2
	CheckinStatus_CHECKIN_STATUS_REJECTED    CheckinStatus = 3
	CheckinStatus_CHECKIN_STATUS_EXPIRED     CheckinStatus = 4
)

// Enum value maps for CheckinStatus.
var (
	CheckinStatus_name = map[int32]string{
		0: "CHECKIN_STATUS_UNSPECIFIED",
		1: "CHECKIN_STATUS_PENDING",
		2: "CHECKIN_STATUS_APPROVED",
		3: "CHECKIN_STATUS_REJECTED",
		4: "CHECKIN_STATUS_EXPIRED",
	}
	CheckinStatus_value = map[string]int32{
		"CHECKIN_STATUS_UNSPECIFIED": 0,
		"CHECKIN_STATUS_PENDING":     1,
		"CHECKIN_STATUS_APPROVED":    2,
		"CHECKIN_STATUS_REJECTED":    3,
		"CHECKIN_STATUS_EXPIRED":     4,
	}
)

func (x CheckinStatus) Enum() *CheckinStatus {
	p := new(CheckinStatus)
	*p = x
	return p
}

func (x CheckinStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckinStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_buddygym_v1_checkin_proto_enumTypes[0].Descriptor()
}

func (CheckinStatus) Type() protoreflect.EnumType {
	return &file_buddygym_v1_checkin_proto_enumTypes[0]
}

func (x CheckinStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckinStatus.Descriptor instead.
func (CheckinStatus) EnumDescriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{0}
}

type GeoPoint struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Lat                float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	HorizontalAccuracy float64                `protobuf:"fixed64,3,opt,name=horizontal_accuracy,json=horizontalAccuracy,proto3" json:"horizontal_accuracy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{0}
}

func (x *GeoPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoPoint) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoPoint) GetHorizontalAccuracy() float64 {
	if x != nil {
		return x.HorizontalAccuracy
	}
	return 0
}

type Checkin struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status CheckinStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=buddygym.v1.CheckinStatus" json:"status,omitempty"`
	// object storage key, not a URL: the bucket stays private and core proxies the bytes
	PhotoKey      string                 `protobuf:"bytes,5,opt,name=photo_key,json=photoKey,proto3" json:"photo_key,omitempty"`
	Geo           *GeoPoint              `protobuf:"bytes,6,opt,name=geo,proto3" json:"geo,omitempty"`
	VotesApprove  int32                  `protobuf:"varint,7,opt,name=votes_approve,json=votesApprove,proto3" json:"votes_approve,omitempty"`
	VotesReject   int32                  `protobuf:"varint,8,opt,name=votes_reject,json=votesReject,proto3" json:"votes_reject,omitempty"`
	VotesRequired int32                  `protobuf:"varint,9,opt,name=votes_required,json=votesRequired,proto3" json:"votes_required,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// photos are retained for a fixed window, then purged by a background job.
	// a shared photo is only purged once every checkin using it has aged out.
	PhotoExpiresAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=photo_expires_at,json=photoExpiresAt,proto3" json:"photo_expires_at,omitempty"`
	PhotoPurged    bool                   `protobuf:"varint,13,opt,name=photo_purged,json=photoPurged,proto3" json:"photo_purged,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Checkin) Reset() {
	*x = Checkin{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkin) ProtoMessage() {}

func (x *Checkin) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkin.ProtoReflect.Descriptor instead.
func (*Checkin) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{1}
}

func (x *Checkin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkin) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Checkin) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Checkin) GetStatus() CheckinStatus {
	if x != nil {
		return x.Status
	}
	return CheckinStatus_CHECKIN_STATUS_UNSPECIFIED
}

func (x *Checkin) GetPhotoKey() string {
	if x != nil {
		return x.PhotoKey
	}
	return ""
}

func (x *Checkin) GetGeo() *GeoPoint {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Checkin) GetVotesApprove() int32 {
	if x != nil {
		return x.VotesApprove
	}
	return 0
}

func (x *Checkin) GetVotesReject() int32 {
	if x != nil {
		return x.VotesReject
	}
	return 0
}

func (x *Checkin) GetVotesRequired() int32 {
	if x != nil {
		return x.VotesRequired
	}
	return 0
}

func (x *Checkin) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Checkin) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Checkin) GetPhotoExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PhotoExpiresAt
	}
	return nil
}

func (x *Checkin) GetPhotoPurged() bool {
	if x != nil {
		return x.PhotoPurged
	}
	return false
}

// One room the proof is submitted to. Quorum is per room, so it travels with the target.
type CheckinTarget struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoomId int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// decided by core from room settings
	VotesRequired int32 `protobuf:"varint,2,opt,name=votes_required,json=votesRequired,proto3" json:"votes_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckinTarget) Reset() {
	*x = CheckinTarget{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinTarget) ProtoMessage() {}

func (x *CheckinTarget) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinTarget.ProtoReflect.Descriptor instead.
func (*CheckinTarget) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{2}
}

func (x *CheckinTarget) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CheckinTarget) GetVotesRequired() int32 {
	if x != nil {
		return x.VotesRequired
	}
	return 0
}

// One workout proof, submitted to one or more rooms at once. A photo is uploaded
// once and shared by every checkin created from this request.
type CreateCheckinRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Targets []*CheckinTarget       `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	// Types that are valid to be assigned to Proof:
	//
	//	*CreateCheckinRequest_Photo
	//	*CreateCheckinRequest_Geo
	Proof         isCreateCheckinRequest_Proof `protobuf_oneof:"proof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckinRequest) Reset() {
	*x = CreateCheckinRequest{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckinRequest) ProtoMessage() {}

func (x *CreateCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckinRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckinRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCheckinRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCheckinRequest) GetTargets() []*CheckinTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CreateCheckinRequest) GetProof() isCreateCheckinRequest_Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *CreateCheckinRequest) GetPhoto() []byte {
	if x != nil {
		if x, ok := x.Proof.(*CreateCheckinRequest_Photo); ok {
			return x.Photo
		}
	}
	return nil
}

func (x *CreateCheckinRequest) GetGeo() *GeoPoint {
	if x != nil {
		if x, ok := x.Proof.(*CreateCheckinRequest_Geo); ok {
			return x.Geo
		}
	}
	return nil
}

type isCreateCheckinRequest_Proof interface {
	isCreateCheckinRequest_Proof()
}

type CreateCheckinRequest_Photo struct {
	Photo []byte `protobuf:"bytes,3,opt,name=photo,proto3,oneof"`
}

type CreateCheckinRequest_Geo struct {
	Geo *GeoPoint `protobuf:"bytes,4,opt,name=geo,proto3,oneof"`
}

func (*CreateCheckinRequest_Photo) isCreateCheckinRequest_Proof() {}

func (*CreateCheckinRequest_Geo) isCreateCheckinRequest_Proof() {}

type CreateCheckinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// one checkin per target, in the same order
	Checkins      []*Checkin `protobuf:"bytes,1,rep,name=checkins,proto3" json:"checkins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckinResponse) Reset() {
	*x = CreateCheckinResponse{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckinResponse) ProtoMessage() {}

func (x *CreateCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckinResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckinResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCheckinResponse) GetCheckins() []*Checkin {
	if x != nil {
		return x.Checkins
	}
	return nil
}

type GetCheckinPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckinId     string                 `protobuf:"bytes,1,opt,name=checkin_id,json=checkinId,proto3" json:"checkin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckinPhotoRequest) Reset() {
	*x = GetCheckinPhotoRequest{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckinPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinPhotoRequest) ProtoMessage() {}

func (x *GetCheckinPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetCheckinPhotoRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{5}
}

func (x *GetCheckinPhotoRequest) GetCheckinId() string {
	if x != nil {
		return x.CheckinId
	}
	return ""
}

type CheckinPhotoChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// sniffed on upload, sent on the first chunk only
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckinPhotoChunk) Reset() {
	*x = CheckinPhotoChunk{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinPhotoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinPhotoChunk) ProtoMessage() {}

func (x *CheckinPhotoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinPhotoChunk.ProtoReflect.Descriptor instead.
func (*CheckinPhotoChunk) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{6}
}

func (x *CheckinPhotoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CheckinPhotoChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GetCheckinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckinId     string                 `protobuf:"bytes,1,opt,name=checkin_id,json=checkinId,proto3" json:"checkin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckinRequest) Reset() {
	*x = GetCheckinRequest{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinRequest) ProtoMessage() {}

func (x *GetCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinRequest.ProtoReflect.Descriptor instead.
func (*GetCheckinRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{7}
}

func (x *GetCheckinRequest) GetCheckinId() string {
	if x != nil {
		return x.CheckinId
	}
	return ""
}

type GetCheckinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkin       *Checkin               `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckinResponse) Reset() {
	*x = GetCheckinResponse{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinResponse) ProtoMessage() {}

func (x *GetCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinResponse.ProtoReflect.Descriptor instead.
func (*GetCheckinResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{8}
}

func (x *GetCheckinResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

type ListRoomCheckinsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoomId int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// unspecified means all statuses
	Status        CheckinStatus `protobuf:"varint,2,opt,name=status,proto3,enum=buddygym.v1.CheckinStatus" json:"status,omitempty"`
	Limit         int32         `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32         `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomCheckinsRequest) Reset() {
	*x = ListRoomCheckinsRequest{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomCheckinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomCheckinsRequest) ProtoMessage() {}

func (x *ListRoomCheckinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomCheckinsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomCheckinsRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoomCheckinsRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ListRoomCheckinsRequest) GetStatus() CheckinStatus {
	if x != nil {
		return x.Status
	}
	return CheckinStatus_CHECKIN_STATUS_UNSPECIFIED
}

func (x *ListRoomCheckinsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoomCheckinsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRoomCheckinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkins      []*Checkin             `protobuf:"bytes,1,rep,name=checkins,proto3" json:"checkins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomCheckinsResponse) Reset() {
	*x = ListRoomCheckinsResponse{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomCheckinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomCheckinsResponse) ProtoMessage() {}

func (x *ListRoomCheckinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomCheckinsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomCheckinsResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoomCheckinsResponse) GetCheckins() []*Checkin {
	if x != nil {
		return x.Checkins
	}
	return nil
}

type CastVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckinId     string                 `protobuf:"bytes,1,opt,name=checkin_id,json=checkinId,proto3" json:"checkin_id,omitempty"`
	VoterId       int64                  `protobuf:"varint,2,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteRequest) Reset() {
	*x = CastVoteRequest{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteRequest) ProtoMessage() {}

func (x *CastVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteRequest.ProtoReflect.Descriptor instead.
func (*CastVoteRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{11}
}

func (x *CastVoteRequest) GetCheckinId() string {
	if x != nil {
		return x.CheckinId
	}
	return ""
}

func (x *CastVoteRequest) GetVoterId() int64 {
	if x != nil {
		return x.VoterId
	}
	return 0
}

func (x *CastVoteRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type CastVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkin       *Checkin               `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteResponse) Reset() {
	*x = CastVoteResponse{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteResponse) ProtoMessage() {}

func (x *CastVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteResponse.ProtoReflect.Descriptor instead.
func (*CastVoteResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{12}
}

func (x *CastVoteResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

type PurgeRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeRoomRequest) Reset() {
	*x = PurgeRoomRequest{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeRoomRequest) ProtoMessage() {}

func (x *PurgeRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeRoomRequest.ProtoReflect.Descriptor instead.
func (*PurgeRoomRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{13}
}

func (x *PurgeRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type PurgeRoomResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckinsDeleted int32                  `protobuf:"varint,1,opt,name=checkins_deleted,json=checkinsDeleted,proto3" json:"checkins_deleted,omitempty"`
	// a shared photo is kept while any checkin in another room still points at it
	PhotosDeleted int32 `protobuf:"varint,2,opt,name=photos_deleted,json=photosDeleted,proto3" json:"photos_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeRoomResponse) Reset() {
	*x = PurgeRoomResponse{}
	mi := &file_buddygym_v1_checkin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeRoomResponse) ProtoMessage() {}

func (x *PurgeRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeRoomResponse.ProtoReflect.Descriptor instead.
func (*PurgeRoomResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{14}
}

func (x *PurgeRoomResponse) GetCheckinsDeleted() int32 {
	if x != nil {
		return x.CheckinsDeleted
	}
	return 0
}

func (x *PurgeRoomResponse) GetPhotosDeleted() int32 {
	if x != nil {
		return x.PhotosDeleted
	}
	return 0
}

var File_buddygym_v1_checkin_proto protoreflect.FileDescriptor

const file_buddygym_v1_checkin_proto_rawDesc = "" +
	"\n" +
	"\x19buddygym/v1/checkin.proto\x12\vbuddygym.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\bGeoPoint\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12/\n" +
	"\x13horizontal_accuracy\x18\x03 \x01(\x01R\x12horizontalAccuracy\"\x93\x04\n" +
	"\aCheckin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.buddygym.v1.CheckinStatusR\x06status\x12\x1b\n" +
	"\tphoto_key\x18\x05 \x01(\tR\bphotoKey\x12'\n" +
	"\x03geo\x18\x06 \x01(\v2\x15.buddygym.v1.GeoPointR\x03geo\x12#\n" +
	"\rvotes_approve\x18\a \x01(\x05R\fvotesApprove\x12!\n" +
	"\fvotes_reject\x18\b \x01(\x05R\vvotesReject\x12%\n" +
	"\x0evotes_required\x18\t \x01(\x05R\rvotesRequired\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12D\n" +
	"\x10photo_expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0ephotoExpiresAt\x12!\n" +
	"\fphoto_purged\x18\r \x01(\bR\vphotoPurged\"O\n" +
	"\rCheckinTarget\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12%\n" +
	"\x0evotes_required\x18\x02 \x01(\x05R\rvotesRequired\"\xb1\x01\n" +
	"\x14CreateCheckinRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x124\n" +
	"\atargets\x18\x02 \x03(\v2\x1a.buddygym.v1.CheckinTargetR\atargets\x12\x16\n" +
	"\x05photo\x18\x03 \x01(\fH\x00R\x05photo\x12)\n" +
	"\x03geo\x18\x04 \x01(\v2\x15.buddygym.v1.GeoPointH\x00R\x03geoB\a\n" +
	"\x05proof\"I\n" +
	"\x15CreateCheckinResponse\x120\n" +
	"\bcheckins\x18\x01 \x03(\v2\x14.buddygym.v1.CheckinR\bcheckins\"7\n" +
	"\x16GetCheckinPhotoRequest\x12\x1d\n" +
	"\n" +
	"checkin_id\x18\x01 \x01(\tR\tcheckinId\"J\n" +
	"\x11CheckinPhotoChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"2\n" +
	"\x11GetCheckinRequest\x12\x1d\n" +
	"\n" +
	"checkin_id\x18\x01 \x01(\tR\tcheckinId\"D\n" +
	"\x12GetCheckinResponse\x12.\n" +
	"\acheckin\x18\x01 \x01(\v2\x14.buddygym.v1.CheckinR\acheckin\"\x94\x01\n" +
	"\x17ListRoomCheckinsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.buddygym.v1.CheckinStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"L\n" +
	"\x18ListRoomCheckinsResponse\x120\n" +
	"\bcheckins\x18\x01 \x03(\v2\x14.buddygym.v1.CheckinR\bcheckins\"e\n" +
	"\x0fCastVoteRequest\x12\x1d\n" +
	"\n" +
	"checkin_id\x18\x01 \x01(\tR\tcheckinId\x12\x19\n" +
	"\bvoter_id\x18\x02 \x01(\x03R\avoterId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\"B\n" +
	"\x10CastVoteResponse\x12.\n" +
	"\acheckin\x18\x01 \x01(\v2\x14.buddygym.v1.CheckinR\acheckin\"+\n" +
	"\x10PurgeRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"e\n" +
	"\x11PurgeRoomResponse\x12)\n" +
	"\x10checkins_deleted\x18\x01 \x01(\x05R\x0fcheckinsDeleted\x12%\n" +
	"\x0ephotos_deleted\x18\x02 \x01(\x05R\rphotosDeleted*\xa1\x01\n" +
	"\rCheckinStatus\x12\x1e\n" +
	"\x1aCHECKIN_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CHECKIN_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17CHECKIN_STATUS_APPROVED\x10\x02\x12\x1b\n" +
	"\x17CHECKIN_STATUS_REJECTED\x10\x03\x12\x1a\n" +
	"\x16CHECKIN_STATUS_EXPIRED\x10\x042\x87\x04\n" +
	"\x0eCheckinService\x12V\n" +
	"\rCreateCheckin\x12!.buddygym.v1.CreateCheckinRequest\x1a\".buddygym.v1.CreateCheckinResponse\x12M\n" +
	"\n" +
	"GetCheckin\x12\x1e.buddygym.v1.GetCheckinRequest\x1a\x1f.buddygym.v1.GetCheckinResponse\x12_\n" +
	"\x10ListRoomCheckins\x12$.buddygym.v1.ListRoomCheckinsRequest\x1a%.buddygym.v1.ListRoomCheckinsResponse\x12G\n" +
	"\bCastVote\x12\x1c.buddygym.v1.CastVoteRequest\x1a\x1d.buddygym.v1.CastVoteResponse\x12X\n" +
	"\x0fGetCheckinPhoto\x12#.buddygym.v1.GetCheckinPhotoRequest\x1a\x1e.buddygym.v1.CheckinPhotoChunk0\x01\x12J\n" +
	"\tPurgeRoom\x12\x1d.buddygym.v1.PurgeRoomRequest\x1a\x1e.buddygym.v1.PurgeRoomResponseBHZFgithub.com/kosttiik/BuddyGym/core-service/internal/pb/buddygym/v1;pbv1b\x06proto3"

var (
	file_buddygym_v1_checkin_proto_rawDescOnce sync.Once
	file_buddygym_v1_checkin_proto_rawDescData []byte
)

func file_buddygym_v1_checkin_proto_rawDescGZIP() []byte {
	file_buddygym_v1_checkin_proto_rawDescOnce.Do(func() {
		file_buddygym_v1_checkin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buddygym_v1_checkin_proto_rawDesc), len(file_buddygym_v1_checkin_proto_rawDesc)))
	})
	return file_buddygym_v1_checkin_proto_rawDescData
}

var file_buddygym_v1_checkin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_buddygym_v1_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_buddygym_v1_checkin_proto_goTypes = []any{
	(CheckinStatus)(0),               // 0: buddygym.v1.CheckinStatus
	(*GeoPoint)(nil),                 // 1: buddygym.v1.GeoPoint
	(*Checkin)(nil),                  // 2: buddygym.v1.Checkin
	(*CheckinTarget)(nil),            // 3: buddygym.v1.CheckinTarget
	(*CreateCheckinRequest)(nil),     // 4: buddygym.v1.CreateCheckinRequest
	(*CreateCheckinResponse)(nil),    // 5: buddygym.v1.CreateCheckinResponse
	(*GetCheckinPhotoRequest)(nil),   // 6: buddygym.v1.GetCheckinPhotoRequest
	(*CheckinPhotoChunk)(nil),        // 7: buddygym.v1.CheckinPhotoChunk
	(*GetCheckinRequest)(nil),        // 8: buddygym.v1.GetCheckinRequest
	(*GetCheckinResponse)(nil),       // 9: buddygym.v1.GetCheckinResponse
	(*ListRoomCheckinsRequest)(nil),  // 10: buddygym.v1.ListRoomCheckinsRequest
	(*ListRoomCheckinsResponse)(nil), // 11: buddygym.v1.ListRoomCheckinsResponse
	(*CastVoteRequest)(nil),          // 12: buddygym.v1.CastVoteRequest
	(*CastVoteResponse)(nil),         // 13: buddygym.v1.CastVoteResponse
	(*PurgeRoomRequest)(nil),         // 14: buddygym.v1.PurgeRoomRequest
	(*PurgeRoomResponse)(nil),        // 15: buddygym.v1.PurgeRoomResponse
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
}
var file_buddygym_v1_checkin_proto_depIdxs = []int32{
	0,  // 0: buddygym.v1.Checkin.status:type_name -> buddygym.v1.CheckinStatus
	1,  // 1: buddygym.v1.Checkin.geo:type_name -> buddygym.v1.GeoPoint
	16, // 2: buddygym.v1.Checkin.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: buddygym.v1.Checkin.expires_at:type_name -> google.protobuf.Timestamp
	16, // 4: buddygym.v1.Checkin.photo_expires_at:type_name -> google.protobuf.Timestamp
	3,  // 5: buddygym.v1.CreateCheckinRequest.targets:type_name -> buddygym.v1.CheckinTarget
	1,  // 6: buddygym.v1.CreateCheckinRequest.geo:type_name -> buddygym.v1.GeoPoint
	2,  // 7: buddygym.v1.CreateCheckinResponse.checkins:type_name -> buddygym.v1.Checkin
	2,  // 8: buddygym.v1.GetCheckinResponse.checkin:type_name -> buddygym.v1.Checkin
	0,  // 9: buddygym.v1.ListRoomCheckinsRequest.status:type_name -> buddygym.v1.CheckinStatus
	2,  // 10: buddygym.v1.ListRoomCheckinsResponse.checkins:type_name -> buddygym.v1.Checkin
	2,  // 11: buddygym.v1.CastVoteResponse.checkin:type_name -> buddygym.v1.Checkin
	4,  // 12: buddygym.v1.CheckinService.CreateCheckin:input_type -> buddygym.v1.CreateCheckinRequest
	8,  // 13: buddygym.v1.CheckinService.GetCheckin:input_type -> buddygym.v1.GetCheckinRequest
	10, // 14: buddygym.v1.CheckinService.ListRoomCheckins:input_type -> buddygym.v1.ListRoomCheckinsRequest
	12, // 15: buddygym.v1.CheckinService.CastVote:input_type -> buddygym.v1.CastVoteRequest
	6,  // 16: buddygym.v1.CheckinService.GetCheckinPhoto:input_type -> buddygym.v1.GetCheckinPhotoRequest
	14, // 17: buddygym.v1.CheckinService.PurgeRoom:input_type -> buddygym.v1.PurgeRoomRequest
	5,  // 18: buddygym.v1.CheckinService.CreateCheckin:output_type -> buddygym.v1.CreateCheckinResponse
	9,  // 19: buddygym.v1.CheckinService.GetCheckin:output_type -> buddygym.v1.GetCheckinResponse
	11, // 20: buddygym.v1.CheckinService.ListRoomCheckins:output_type -> buddygym.v1.ListRoomCheckinsResponse
	13, // 21: buddygym.v1.CheckinService.CastVote:output_type -> buddygym.v1.CastVoteResponse
	7,  // 22: buddygym.v1.CheckinService.GetCheckinPhoto:output_type -> buddygym.v1.CheckinPhotoChunk
	15, // 23: buddygym.v1.CheckinService.PurgeRoom:output_type -> buddygym.v1.PurgeRoomResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_buddygym_v1_checkin_proto_init() }
func file_buddygym_v1_checkin_proto_init() {
	if File_buddygym_v1_checkin_proto != nil {
		return
	}
	file_buddygym_v1_checkin_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateCheckinRequest_Photo)(nil),
		(*CreateCheckinRequest_Geo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buddygym_v1_checkin_proto_rawDesc), len(file_buddygym_v1_checkin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buddygym_v1_checkin_proto_goTypes,
		DependencyIndexes: file_buddygym_v1_checkin_proto_depIdxs,
		EnumInfos:         file_buddygym_v1_checkin_proto_enumTypes,
		MessageInfos:      file_buddygym_v1_checkin_proto_msgTypes,
	}.Build()
	File_buddygym_v1_checkin_proto = out.File
	file_buddygym_v1_checkin_proto_goTypes = nil
	file_buddygym_v1_checkin_proto_depIdxs = nil
}
