// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v7.35.1
// source: buddygym/v1/checkin.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckinStatus int32

const (
	CheckinStatus_CHECKIN_STATUS_UNSPECIFIED CheckinStatus = 0
	CheckinStatus_CHECKIN_STATUS_PENDING     CheckinStatus = 1
	CheckinStatus_CHECKIN_STATUS_APPROVED    CheckinStatus = 2
	CheckinStatus_CHECKIN_STATUS_REJECTED    CheckinStatus = 3
	CheckinStatus_CHECKIN_STATUS_EXPIRED     CheckinStatus = 4
)

// Enum value maps for CheckinStatus.
var (
	CheckinStatus_name = map[int32]string{
		0: "CHECKIN_STATUS_UNSPECIFIED",
		1: "CHECKIN_STATUS_PENDING",
		2: "CHECKIN_STATUS_APPROVED",
		3: "CHECKIN_STATUS_REJECTED",
		4: "CHECKIN_STATUS_EXPIRED",
	}
	CheckinStatus_value = map[string]int32{
		"CHECKIN_STATUS_UNSPECIFIED": 0,
		"CHECKIN_STATUS_PENDING":     1,
		"CHECKIN_STATUS_APPROVED":    2,
		"CHECKIN_STATUS_REJECTED":    3,
		"CHECKIN_STATUS_EXPIRED":     4,
	}
)

func (x CheckinStatus) Enum() *CheckinStatus {
	p := new(CheckinStatus)
	*p = x
	return p
}

func (x CheckinStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckinStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_buddygym_v1_checkin_proto_enumTypes[0].Descriptor()
}

func (CheckinStatus) Type() protoreflect.EnumType {
	return &file_buddygym_v1_checkin_proto_enumTypes[0]
}

func (x CheckinStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckinStatus.Descriptor instead.
func (CheckinStatus) EnumDescriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{0}
}

type GeoPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat                float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	HorizontalAccuracy float64 `protobuf:"fixed64,3,opt,name=horizontal_accuracy,json=horizontalAccuracy,proto3" json:"horizontal_accuracy,omitempty"`
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{0}
}

func (x *GeoPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoPoint) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoPoint) GetHorizontalAccuracy() float64 {
	if x != nil {
		return x.HorizontalAccuracy
	}
	return 0
}

type Checkin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId int64         `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId int64         `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status CheckinStatus `protobuf:"varint,4,opt,name=status,proto3,enum=buddygym.v1.CheckinStatus" json:"status,omitempty"`
	// object storage key, not a URL: the bucket stays private and core proxies the bytes
	PhotoKey      string                 `protobuf:"bytes,5,opt,name=photo_key,json=photoKey,proto3" json:"photo_key,omitempty"`
	Geo           *GeoPoint              `protobuf:"bytes,6,opt,name=geo,proto3" json:"geo,omitempty"`
	VotesApprove  int32                  `protobuf:"varint,7,opt,name=votes_approve,json=votesApprove,proto3" json:"votes_approve,omitempty"`
	VotesReject   int32                  `protobuf:"varint,8,opt,name=votes_reject,json=votesReject,proto3" json:"votes_reject,omitempty"`
	VotesRequired int32                  `protobuf:"varint,9,opt,name=votes_required,json=votesRequired,proto3" json:"votes_required,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// photos are retained for a fixed window, then purged by a background job.
	// a shared photo is only purged once every checkin using it has aged out.
	PhotoExpiresAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=photo_expires_at,json=photoExpiresAt,proto3" json:"photo_expires_at,omitempty"`
	PhotoPurged    bool                   `protobuf:"varint,13,opt,name=photo_purged,json=photoPurged,proto3" json:"photo_purged,omitempty"`
}

func (x *Checkin) Reset() {
	*x = Checkin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkin) ProtoMessage() {}

func (x *Checkin) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkin.ProtoReflect.Descriptor instead.
func (*Checkin) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{1}
}

func (x *Checkin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkin) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Checkin) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Checkin) GetStatus() CheckinStatus {
	if x != nil {
		return x.Status
	}
	return CheckinStatus_CHECKIN_STATUS_UNSPECIFIED
}

func (x *Checkin) GetPhotoKey() string {
	if x != nil {
		return x.PhotoKey
	}
	return ""
}

func (x *Checkin) GetGeo() *GeoPoint {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Checkin) GetVotesApprove() int32 {
	if x != nil {
		return x.VotesApprove
	}
	return 0
}

func (x *Checkin) GetVotesReject() int32 {
	if x != nil {
		return x.VotesReject
	}
	return 0
}

func (x *Checkin) GetVotesRequired() int32 {
	if x != nil {
		return x.VotesRequired
	}
	return 0
}

func (x *Checkin) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Checkin) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Checkin) GetPhotoExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PhotoExpiresAt
	}
	return nil
}

func (x *Checkin) GetPhotoPurged() bool {
	if x != nil {
		return x.PhotoPurged
	}
	return false
}

// One room the proof is submitted to. Quorum is per room, so it travels with the target.
type CheckinTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// decided by core from room settings
	VotesRequired int32 `protobuf:"varint,2,opt,name=votes_required,json=votesRequired,proto3" json:"votes_required,omitempty"`
}

func (x *CheckinTarget) Reset() {
	*x = CheckinTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckinTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinTarget) ProtoMessage() {}

func (x *CheckinTarget) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinTarget.ProtoReflect.Descriptor instead.
func (*CheckinTarget) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{2}
}

func (x *CheckinTarget) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CheckinTarget) GetVotesRequired() int32 {
	if x != nil {
		return x.VotesRequired
	}
	return 0
}

// One workout proof, submitted to one or more rooms at once. A photo is uploaded
// once and shared by every checkin created from this request.
type CreateCheckinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64            `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Targets []*CheckinTarget `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	// Types that are assignable to Proof:
	//
	//	*CreateCheckinRequest_Photo
	//	*CreateCheckinRequest_Geo
	Proof isCreateCheckinRequest_Proof `protobuf_oneof:"proof"`
}

func (x *CreateCheckinRequest) Reset() {
	*x = CreateCheckinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckinRequest) ProtoMessage() {}

func (x *CreateCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckinRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckinRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCheckinRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCheckinRequest) GetTargets() []*CheckinTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (m *CreateCheckinRequest) GetProof() isCreateCheckinRequest_Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (x *CreateCheckinRequest) GetPhoto() []byte {
	if x, ok := x.GetProof().(*CreateCheckinRequest_Photo); ok {
		return x.Photo
	}
	return nil
}

func (x *CreateCheckinRequest) GetGeo() *GeoPoint {
	if x, ok := x.GetProof().(*CreateCheckinRequest_Geo); ok {
		return x.Geo
	}
	return nil
}

type isCreateCheckinRequest_Proof interface {
	isCreateCheckinRequest_Proof()
}

type CreateCheckinRequest_Photo struct {
	Photo []byte `protobuf:"bytes,3,opt,name=photo,proto3,oneof"`
}

type CreateCheckinRequest_Geo struct {
	Geo *GeoPoint `protobuf:"bytes,4,opt,name=geo,proto3,oneof"`
}

func (*CreateCheckinRequest_Photo) isCreateCheckinRequest_Proof() {}

func (*CreateCheckinRequest_Geo) isCreateCheckinRequest_Proof() {}

type CreateCheckinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// one checkin per target, in the same order
	Checkins []*Checkin `protobuf:"bytes,1,rep,name=checkins,proto3" json:"checkins,omitempty"`
}

func (x *CreateCheckinResponse) Reset() {
	*x = CreateCheckinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckinResponse) ProtoMessage() {}

func (x *CreateCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckinResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckinResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCheckinResponse) GetCheckins() []*Checkin {
	if x != nil {
		return x.Checkins
	}
	return nil
}

type GetCheckinPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckinId string `protobuf:"bytes,1,opt,name=checkin_id,json=checkinId,proto3" json:"checkin_id,omitempty"`
}

func (x *GetCheckinPhotoRequest) Reset() {
	*x = GetCheckinPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCheckinPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinPhotoRequest) ProtoMessage() {}

func (x *GetCheckinPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetCheckinPhotoRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{5}
}

func (x *GetCheckinPhotoRequest) GetCheckinId() string {
	if x != nil {
		return x.CheckinId
	}
	return ""
}

type CheckinPhotoChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// sniffed on upload, sent on the first chunk only
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
}

func (x *CheckinPhotoChunk) Reset() {
	*x = CheckinPhotoChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckinPhotoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinPhotoChunk) ProtoMessage() {}

func (x *CheckinPhotoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinPhotoChunk.ProtoReflect.Descriptor instead.
func (*CheckinPhotoChunk) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{6}
}

func (x *CheckinPhotoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CheckinPhotoChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GetCheckinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckinId string `protobuf:"bytes,1,opt,name=checkin_id,json=checkinId,proto3" json:"checkin_id,omitempty"`
}

func (x *GetCheckinRequest) Reset() {
	*x = GetCheckinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinRequest) ProtoMessage() {}

func (x *GetCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinRequest.ProtoReflect.Descriptor instead.
func (*GetCheckinRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{7}
}

func (x *GetCheckinRequest) GetCheckinId() string {
	if x != nil {
		return x.CheckinId
	}
	return ""
}

type GetCheckinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkin *Checkin `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
}

func (x *GetCheckinResponse) Reset() {
	*x = GetCheckinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinResponse) ProtoMessage() {}

func (x *GetCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinResponse.ProtoReflect.Descriptor instead.
func (*GetCheckinResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{8}
}

func (x *GetCheckinResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

type ListRoomCheckinsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// unspecified means all statuses
	Status CheckinStatus `protobuf:"varint,2,opt,name=status,proto3,enum=buddygym.v1.CheckinStatus" json:"status,omitempty"`
	Limit  int32         `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32         `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListRoomCheckinsRequest) Reset() {
	*x = ListRoomCheckinsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoomCheckinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomCheckinsRequest) ProtoMessage() {}

func (x *ListRoomCheckinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomCheckinsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomCheckinsRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoomCheckinsRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ListRoomCheckinsRequest) GetStatus() CheckinStatus {
	if x != nil {
		return x.Status
	}
	return CheckinStatus_CHECKIN_STATUS_UNSPECIFIED
}

func (x *ListRoomCheckinsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoomCheckinsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRoomCheckinsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkins []*Checkin `protobuf:"bytes,1,rep,name=checkins,proto3" json:"checkins,omitempty"`
}

func (x *ListRoomCheckinsResponse) Reset() {
	*x = ListRoomCheckinsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoomCheckinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomCheckinsResponse) ProtoMessage() {}

func (x *ListRoomCheckinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomCheckinsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomCheckinsResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoomCheckinsResponse) GetCheckins() []*Checkin {
	if x != nil {
		return x.Checkins
	}
	return nil
}

type CastVoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckinId string `protobuf:"bytes,1,opt,name=checkin_id,json=checkinId,proto3" json:"checkin_id,omitempty"`
	VoterId   int64  `protobuf:"varint,2,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	Approve   bool   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
}

func (x *CastVoteRequest) Reset() {
	*x = CastVoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteRequest) ProtoMessage() {}

func (x *CastVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteRequest.ProtoReflect.Descriptor instead.
func (*CastVoteRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{11}
}

func (x *CastVoteRequest) GetCheckinId() string {
	if x != nil {
		return x.CheckinId
	}
	return ""
}

func (x *CastVoteRequest) GetVoterId() int64 {
	if x != nil {
		return x.VoterId
	}
	return 0
}

func (x *CastVoteRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type CastVoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkin *Checkin `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
}

func (x *CastVoteResponse) Reset() {
	*x = CastVoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteResponse) ProtoMessage() {}

func (x *CastVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteResponse.ProtoReflect.Descriptor instead.
func (*CastVoteResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{12}
}

func (x *CastVoteResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

type CancelCheckinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckinId string `protobuf:"bytes,1,opt,name=checkin_id,json=checkinId,proto3" json:"checkin_id,omitempty"`
	// only the author may cancel, and only while the checkin is still pending
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CancelCheckinRequest) Reset() {
	*x = CancelCheckinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCheckinRequest) ProtoMessage() {}

func (x *CancelCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCheckinRequest.ProtoReflect.Descriptor instead.
func (*CancelCheckinRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{13}
}

func (x *CancelCheckinRequest) GetCheckinId() string {
	if x != nil {
		return x.CheckinId
	}
	return ""
}

func (x *CancelCheckinRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelCheckinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkin *Checkin `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
}

func (x *CancelCheckinResponse) Reset() {
	*x = CancelCheckinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCheckinResponse) ProtoMessage() {}

func (x *CancelCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCheckinResponse.ProtoReflect.Descriptor instead.
func (*CancelCheckinResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{14}
}

func (x *CancelCheckinResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

type PurgeRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *PurgeRoomRequest) Reset() {
	*x = PurgeRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurgeRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeRoomRequest) ProtoMessage() {}

func (x *PurgeRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeRoomRequest.ProtoReflect.Descriptor instead.
func (*PurgeRoomRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{15}
}

func (x *PurgeRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type PurgeRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckinsDeleted int32 `protobuf:"varint,1,opt,name=checkins_deleted,json=checkinsDeleted,proto3" json:"checkins_deleted,omitempty"`
	// a shared photo is kept while any checkin in another room still points at it
	PhotosDeleted int32 `protobuf:"varint,2,opt,name=photos_deleted,json=photosDeleted,proto3" json:"photos_deleted,omitempty"`
}

func (x *PurgeRoomResponse) Reset() {
	*x = PurgeRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurgeRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeRoomResponse) ProtoMessage() {}

func (x *PurgeRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeRoomResponse.ProtoReflect.Descriptor instead.
func (*PurgeRoomResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{16}
}

func (x *PurgeRoomResponse) GetCheckinsDeleted() int32 {
	if x != nil {
		return x.CheckinsDeleted
	}
	return 0
}

func (x *PurgeRoomResponse) GetPhotosDeleted() int32 {
	if x != nil {
		return x.PhotosDeleted
	}
	return 0
}

type SyncRoomVotesRequiredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId        int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	VotesRequired int32 `protobuf:"varint,2,opt,name=votes_required,json=votesRequired,proto3" json:"votes_required,omitempty"`
}

func (x *SyncRoomVotesRequiredRequest) Reset() {
	*x = SyncRoomVotesRequiredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRoomVotesRequiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomVotesRequiredRequest) ProtoMessage() {}

func (x *SyncRoomVotesRequiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomVotesRequiredRequest.ProtoReflect.Descriptor instead.
func (*SyncRoomVotesRequiredRequest) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{17}
}

func (x *SyncRoomVotesRequiredRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SyncRoomVotesRequiredRequest) GetVotesRequired() int32 {
	if x != nil {
		return x.VotesRequired
	}
	return 0
}

type SyncRoomVotesRequiredResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pending checkins that got the new quorum
	Updated int32 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	// of those, how many finalized right away
	Finalized int32 `protobuf:"varint,2,opt,name=finalized,proto3" json:"finalized,omitempty"`
}

func (x *SyncRoomVotesRequiredResponse) Reset() {
	*x = SyncRoomVotesRequiredResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buddygym_v1_checkin_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRoomVotesRequiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomVotesRequiredResponse) ProtoMessage() {}

func (x *SyncRoomVotesRequiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buddygym_v1_checkin_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomVotesRequiredResponse.ProtoReflect.Descriptor instead.
func (*SyncRoomVotesRequiredResponse) Descriptor() ([]byte, []int) {
	return file_buddygym_v1_checkin_proto_rawDescGZIP(), []int{18}
}

func (x *SyncRoomVotesRequiredResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *SyncRoomVotesRequiredResponse) GetFinalized() int32 {
	if x != nil {
		return x.Finalized
	}
	return 0
}

var File_buddygym_v1_checkin_proto protoreflect.FileDescriptor

var file_buddygym_v1_checkin_proto_rawDesc = []byte{
	0x0a, 0x19, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x75, 0x64,
	0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x08, 0x47, 0x65, 0x6f,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x13, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74,
	0x61, 0x6c, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x22, 0x93, 0x04, 0x0a, 0x07, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79,
	0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x03, 0x67, 0x65, 0x6f,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x03, 0x67,
	0x65, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x73,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x73,
	0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76,
	0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x6f,
	0x74, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x44, 0x0a, 0x10, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x75, 0x72, 0x67, 0x65, 0x64, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x50, 0x75, 0x72, 0x67, 0x65, 0x64,
	0x22, 0x4f, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x6f,
	0x74, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x22, 0xb1, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x12, 0x29, 0x0a, 0x03, 0x67, 0x65, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6f,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x03, 0x67, 0x65, 0x6f, 0x42, 0x07, 0x0a, 0x05,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x49, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73,
	0x22, 0x37, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x11, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x22,
	0x94, 0x01, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x4c, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x73, 0x22, 0x65, 0x0a, 0x0f, 0x43, 0x61, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x22, 0x42, 0x0a, 0x10, 0x43,
	0x61, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x22,
	0x4e, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x47, 0x0a, 0x15, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x64, 0x64,
	0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52,
	0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x22, 0x2b, 0x0a, 0x10, 0x50, 0x75, 0x72, 0x67,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x65, 0x0a, 0x11, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x5f,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x5e, 0x0a, 0x1c,
	0x53, 0x79, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x76,
	0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x57, 0x0a, 0x1d,
	0x53, 0x79, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x2a, 0xa1, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x48, 0x45, 0x43, 0x4b,
	0x49, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x48, 0x45, 0x43, 0x4b,
	0x49, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x49, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x1b, 0x0a, 0x17, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x49, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1a, 0x0a,
	0x16, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x49, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x04, 0x32, 0xcf, 0x05, 0x0a, 0x0e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x12, 0x21, 0x2e,
	0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x12, 0x24, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67,
	0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x08, 0x43, 0x61, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65,
	0x12, 0x1c, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x61, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x73,
	0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x12, 0x23, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12, 0x4a, 0x0a, 0x09, 0x50, 0x75, 0x72, 0x67, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1d, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x15, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x56,
	0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x29, 0x2e, 0x62,
	0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x6f, 0x6f, 0x6d, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67,
	0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x6f,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x12, 0x21, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67,
	0x79, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x48, 0x5a, 0x46, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x73, 0x74, 0x74, 0x69,
	0x69, 0x6b, 0x2f, 0x42, 0x75, 0x64, 0x64, 0x79, 0x47, 0x79, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x75, 0x64, 0x64, 0x79, 0x67, 0x79, 0x6d, 0x2f, 0x76, 0x31,
	0x3b, 0x70, 0x62, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buddygym_v1_checkin_proto_rawDescOnce sync.Once
	file_buddygym_v1_checkin_proto_rawDescData = file_buddygym_v1_checkin_proto_rawDesc
)

func file_buddygym_v1_checkin_proto_rawDescGZIP() []byte {
	file_buddygym_v1_checkin_proto_rawDescOnce.Do(func() {
		file_buddygym_v1_checkin_proto_rawDescData = protoimpl.X.CompressGZIP(file_buddygym_v1_checkin_proto_rawDescData)
	})
	return file_buddygym_v1_checkin_proto_rawDescData
}

var file_buddygym_v1_checkin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_buddygym_v1_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_buddygym_v1_checkin_proto_goTypes = []interface{}{
	(CheckinStatus)(0),                    // 0: buddygym.v1.CheckinStatus
	(*GeoPoint)(nil),                      // 1: buddygym.v1.GeoPoint
	(*Checkin)(nil),                       // 2: buddygym.v1.Checkin
	(*CheckinTarget)(nil),                 // 3: buddygym.v1.CheckinTarget
	(*CreateCheckinRequest)(nil),          // 4: buddygym.v1.CreateCheckinRequest
	(*CreateCheckinResponse)(nil),         // 5: buddygym.v1.CreateCheckinResponse
	(*GetCheckinPhotoRequest)(nil),        // 6: buddygym.v1.GetCheckinPhotoRequest
	(*CheckinPhotoChunk)(nil),             // 7: buddygym.v1.CheckinPhotoChunk
	(*GetCheckinRequest)(nil),             // 8: buddygym.v1.GetCheckinRequest
	(*GetCheckinResponse)(nil),            // 9: buddygym.v1.GetCheckinResponse
	(*ListRoomCheckinsRequest)(nil),       // 10: buddygym.v1.ListRoomCheckinsRequest
	(*ListRoomCheckinsResponse)(nil),      // 11: buddygym.v1.ListRoomCheckinsResponse
	(*CastVoteRequest)(nil),               // 12: buddygym.v1.CastVoteRequest
	(*CastVoteResponse)(nil),              // 13: buddygym.v1.CastVoteResponse
	(*CancelCheckinRequest)(nil),          // 14: buddygym.v1.CancelCheckinRequest
	(*CancelCheckinResponse)(nil),         // 15: buddygym.v1.CancelCheckinResponse
	(*PurgeRoomRequest)(nil),              // 16: buddygym.v1.PurgeRoomRequest
	(*PurgeRoomResponse)(nil),             // 17: buddygym.v1.PurgeRoomResponse
	(*SyncRoomVotesRequiredRequest)(nil),  // 18: buddygym.v1.SyncRoomVotesRequiredRequest
	(*SyncRoomVotesRequiredResponse)(nil), // 19: buddygym.v1.SyncRoomVotesRequiredResponse
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
}
var file_buddygym_v1_checkin_proto_depIdxs = []int32{
	0,  // 0: buddygym.v1.Checkin.status:type_name -> buddygym.v1.CheckinStatus
	1,  // 1: buddygym.v1.Checkin.geo:type_name -> buddygym.v1.GeoPoint
	20, // 2: buddygym.v1.Checkin.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: buddygym.v1.Checkin.expires_at:type_name -> google.protobuf.Timestamp
	20, // 4: buddygym.v1.Checkin.photo_expires_at:type_name -> google.protobuf.Timestamp
	3,  // 5: buddygym.v1.CreateCheckinRequest.targets:type_name -> buddygym.v1.CheckinTarget
	1,  // 6: buddygym.v1.CreateCheckinRequest.geo:type_name -> buddygym.v1.GeoPoint
	2,  // 7: buddygym.v1.CreateCheckinResponse.checkins:type_name -> buddygym.v1.Checkin
	2,  // 8: buddygym.v1.GetCheckinResponse.checkin:type_name -> buddygym.v1.Checkin
	0,  // 9: buddygym.v1.ListRoomCheckinsRequest.status:type_name -> buddygym.v1.CheckinStatus
	2,  // 10: buddygym.v1.ListRoomCheckinsResponse.checkins:type_name -> buddygym.v1.Checkin
	2,  // 11: buddygym.v1.CastVoteResponse.checkin:type_name -> buddygym.v1.Checkin
	2,  // 12: buddygym.v1.CancelCheckinResponse.checkin:type_name -> buddygym.v1.Checkin
	4,  // 13: buddygym.v1.CheckinService.CreateCheckin:input_type -> buddygym.v1.CreateCheckinRequest
	8,  // 14: buddygym.v1.CheckinService.GetCheckin:input_type -> buddygym.v1.GetCheckinRequest
	10, // 15: buddygym.v1.CheckinService.ListRoomCheckins:input_type -> buddygym.v1.ListRoomCheckinsRequest
	12, // 16: buddygym.v1.CheckinService.CastVote:input_type -> buddygym.v1.CastVoteRequest
	6,  // 17: buddygym.v1.CheckinService.GetCheckinPhoto:input_type -> buddygym.v1.GetCheckinPhotoRequest
	16, // 18: buddygym.v1.CheckinService.PurgeRoom:input_type -> buddygym.v1.PurgeRoomRequest
	18, // 19: buddygym.v1.CheckinService.SyncRoomVotesRequired:input_type -> buddygym.v1.SyncRoomVotesRequiredRequest
	14, // 20: buddygym.v1.CheckinService.CancelCheckin:input_type -> buddygym.v1.CancelCheckinRequest
	5,  // 21: buddygym.v1.CheckinService.CreateCheckin:output_type -> buddygym.v1.CreateCheckinResponse
	9,  // 22: buddygym.v1.CheckinService.GetCheckin:output_type -> buddygym.v1.GetCheckinResponse
	11, // 23: buddygym.v1.CheckinService.ListRoomCheckins:output_type -> buddygym.v1.ListRoomCheckinsResponse
	13, // 24: buddygym.v1.CheckinService.CastVote:output_type -> buddygym.v1.CastVoteResponse
	7,  // 25: buddygym.v1.CheckinService.GetCheckinPhoto:output_type -> buddygym.v1.CheckinPhotoChunk
	17, // 26: buddygym.v1.CheckinService.PurgeRoom:output_type -> buddygym.v1.PurgeRoomResponse
	19, // 27: buddygym.v1.CheckinService.SyncRoomVotesRequired:output_type -> buddygym.v1.SyncRoomVotesRequiredResponse
	15, // 28: buddygym.v1.CheckinService.CancelCheckin:output_type -> buddygym.v1.CancelCheckinResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_buddygym_v1_checkin_proto_init() }
func file_buddygym_v1_checkin_proto_init() {
	if File_buddygym_v1_checkin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buddygym_v1_checkin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckinTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCheckinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCheckinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCheckinPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckinPhotoChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCheckinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCheckinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoomCheckinsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoomCheckinsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastVoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastVoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelCheckinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelCheckinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurgeRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurgeRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRoomVotesRequiredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buddygym_v1_checkin_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRoomVotesRequiredResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_buddygym_v1_checkin_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*CreateCheckinRequest_Photo)(nil),
		(*CreateCheckinRequest_Geo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buddygym_v1_checkin_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buddygym_v1_checkin_proto_goTypes,
		DependencyIndexes: file_buddygym_v1_checkin_proto_depIdxs,
		EnumInfos:         file_buddygym_v1_checkin_proto_enumTypes,
		MessageInfos:      file_buddygym_v1_checkin_proto_msgTypes,
	}.Build()
	File_buddygym_v1_checkin_proto = out.File
	file_buddygym_v1_checkin_proto_rawDesc = nil
	file_buddygym_v1_checkin_proto_goTypes = nil
	file_buddygym_v1_checkin_proto_depIdxs = nil
}
