// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: buddygym/v1/checkin.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckinService_CreateCheckin_FullMethodName    = "/buddygym.v1.CheckinService/CreateCheckin"
	CheckinService_GetCheckin_FullMethodName       = "/buddygym.v1.CheckinService/GetCheckin"
	CheckinService_ListRoomCheckins_FullMethodName = "/buddygym.v1.CheckinService/ListRoomCheckins"
	CheckinService_CastVote_FullMethodName         = "/buddygym.v1.CheckinService/CastVote"
	CheckinService_GetCheckinPhoto_FullMethodName  = "/buddygym.v1.CheckinService/GetCheckinPhoto"
	CheckinService_PurgeRoom_FullMethodName        = "/buddygym.v1.CheckinService/PurgeRoom"
)

// CheckinServiceClient is the client API for CheckinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CheckinService is implemented by checkin-service (Python).
// core-service calls it as a proxy for the frontend.
type CheckinServiceClient interface {
	CreateCheckin(ctx context.Context, in *CreateCheckinRequest, opts ...grpc.CallOption) (*CreateCheckinResponse, error)
	GetCheckin(ctx context.Context, in *GetCheckinRequest, opts ...grpc.CallOption) (*GetCheckinResponse, error)
	ListRoomCheckins(ctx context.Context, in *ListRoomCheckinsRequest, opts ...grpc.CallOption) (*ListRoomCheckinsResponse, error)
	CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error)
	// photos are never public: core streams them to authorized room members
	GetCheckinPhoto(ctx context.Context, in *GetCheckinPhotoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckinPhotoChunk], error)
	// core calls this when a room is gone for good
	PurgeRoom(ctx context.Context, in *PurgeRoomRequest, opts ...grpc.CallOption) (*PurgeRoomResponse, error)
}

type checkinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckinServiceClient(cc grpc.ClientConnInterface) CheckinServiceClient {
	return &checkinServiceClient{cc}
}

func (c *checkinServiceClient) CreateCheckin(ctx context.Context, in *CreateCheckinRequest, opts ...grpc.CallOption) (*CreateCheckinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCheckinResponse)
	err := c.cc.Invoke(ctx, CheckinService_CreateCheckin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) GetCheckin(ctx context.Context, in *GetCheckinRequest, opts ...grpc.CallOption) (*GetCheckinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckinResponse)
	err := c.cc.Invoke(ctx, CheckinService_GetCheckin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) ListRoomCheckins(ctx context.Context, in *ListRoomCheckinsRequest, opts ...grpc.CallOption) (*ListRoomCheckinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomCheckinsResponse)
	err := c.cc.Invoke(ctx, CheckinService_ListRoomCheckins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CastVoteResponse)
	err := c.cc.Invoke(ctx, CheckinService_CastVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) GetCheckinPhoto(ctx context.Context, in *GetCheckinPhotoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckinPhotoChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CheckinService_ServiceDesc.Streams[0], CheckinService_GetCheckinPhoto_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCheckinPhotoRequest, CheckinPhotoChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckinService_GetCheckinPhotoClient = grpc.ServerStreamingClient[CheckinPhotoChunk]

func (c *checkinServiceClient) PurgeRoom(ctx context.Context, in *PurgeRoomRequest, opts ...grpc.CallOption) (*PurgeRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeRoomResponse)
	err := c.cc.Invoke(ctx, CheckinService_PurgeRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckinServiceServer is the server API for CheckinService service.
// All implementations must embed UnimplementedCheckinServiceServer
// for forward compatibility.
//
// CheckinService is implemented by checkin-service (Python).
// core-service calls it as a proxy for the frontend.
type CheckinServiceServer interface {
	CreateCheckin(context.Context, *CreateCheckinRequest) (*CreateCheckinResponse, error)
	GetCheckin(context.Context, *GetCheckinRequest) (*GetCheckinResponse, error)
	ListRoomCheckins(context.Context, *ListRoomCheckinsRequest) (*ListRoomCheckinsResponse, error)
	CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error)
	// photos are never public: core streams them to authorized room members
	GetCheckinPhoto(*GetCheckinPhotoRequest, grpc.ServerStreamingServer[CheckinPhotoChunk]) error
	// core calls this when a room is gone for good
	PurgeRoom(context.Context, *PurgeRoomRequest) (*PurgeRoomResponse, error)
	mustEmbedUnimplementedCheckinServiceServer()
}

// UnimplementedCheckinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckinServiceServer struct{}

func (UnimplementedCheckinServiceServer) CreateCheckin(context.Context, *CreateCheckinRequest) (*CreateCheckinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCheckin not implemented")
}
func (UnimplementedCheckinServiceServer) GetCheckin(context.Context, *GetCheckinRequest) (*GetCheckinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckin not implemented")
}
func (UnimplementedCheckinServiceServer) ListRoomCheckins(context.Context, *ListRoomCheckinsRequest) (*ListRoomCheckinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoomCheckins not implemented")
}
func (UnimplementedCheckinServiceServer) CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastVote not implemented")
}
func (UnimplementedCheckinServiceServer) GetCheckinPhoto(*GetCheckinPhotoRequest, grpc.ServerStreamingServer[CheckinPhotoChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetCheckinPhoto not implemented")
}
func (UnimplementedCheckinServiceServer) PurgeRoom(context.Context, *PurgeRoomRequest) (*PurgeRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeRoom not implemented")
}
func (UnimplementedCheckinServiceServer) mustEmbedUnimplementedCheckinServiceServer() {}
func (UnimplementedCheckinServiceServer) testEmbeddedByValue()                        {}

// UnsafeCheckinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckinServiceServer will
// result in compilation errors.
type UnsafeCheckinServiceServer interface {
	mustEmbedUnimplementedCheckinServiceServer()
}

func RegisterCheckinServiceServer(s grpc.ServiceRegistrar, srv CheckinServiceServer) {
	// If the following call pancis, it indicates UnimplementedCheckinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckinService_ServiceDesc, srv)
}

func _CheckinService_CreateCheckin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).CreateCheckin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckinService_CreateCheckin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).CreateCheckin(ctx, req.(*CreateCheckinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_GetCheckin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).GetCheckin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckinService_GetCheckin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).GetCheckin(ctx, req.(*GetCheckinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_ListRoomCheckins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomCheckinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).ListRoomCheckins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckinService_ListRoomCheckins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).ListRoomCheckins(ctx, req.(*ListRoomCheckinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckinService_CastVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).CastVote(ctx, req.(*CastVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_GetCheckinPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCheckinPhotoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CheckinServiceServer).GetCheckinPhoto(m, &grpc.GenericServerStream[GetCheckinPhotoRequest, CheckinPhotoChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckinService_GetCheckinPhotoServer = grpc.ServerStreamingServer[CheckinPhotoChunk]

func _CheckinService_PurgeRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).PurgeRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckinService_PurgeRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).PurgeRoom(ctx, req.(*PurgeRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckinService_ServiceDesc is the grpc.ServiceDesc for CheckinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buddygym.v1.CheckinService",
	HandlerType: (*CheckinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCheckin",
			Handler:    _CheckinService_CreateCheckin_Handler,
		},
		{
			MethodName: "GetCheckin",
			Handler:    _CheckinService_GetCheckin_Handler,
		},
		{
			MethodName: "ListRoomCheckins",
			Handler:    _CheckinService_ListRoomCheckins_Handler,
		},
		{
			MethodName: "CastVote",
			Handler:    _CheckinService_CastVote_Handler,
		},
		{
			MethodName: "PurgeRoom",
			Handler:    _CheckinService_PurgeRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCheckinPhoto",
			Handler:       _CheckinService_GetCheckinPhoto_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "buddygym/v1/checkin.proto",
}
