// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CheckinServiceClient is the client API for CheckinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckinServiceClient interface {
	CreateCheckin(ctx context.Context, in *CreateCheckinRequest, opts ...grpc.CallOption) (*CreateCheckinResponse, error)
	GetCheckin(ctx context.Context, in *GetCheckinRequest, opts ...grpc.CallOption) (*GetCheckinResponse, error)
	ListRoomCheckins(ctx context.Context, in *ListRoomCheckinsRequest, opts ...grpc.CallOption) (*ListRoomCheckinsResponse, error)
	CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error)
	// photos are never public: core streams them to authorized room members
	GetCheckinPhoto(ctx context.Context, in *GetCheckinPhotoRequest, opts ...grpc.CallOption) (CheckinService_GetCheckinPhotoClient, error)
	// core calls this when a room is gone for good
	PurgeRoom(ctx context.Context, in *PurgeRoomRequest, opts ...grpc.CallOption) (*PurgeRoomResponse, error)
	// core calls this when the room's votes_required changes: pending checkins get the new
	// quorum and are re-finalized against the votes they already hold
	SyncRoomVotesRequired(ctx context.Context, in *SyncRoomVotesRequiredRequest, opts ...grpc.CallOption) (*SyncRoomVotesRequiredResponse, error)
}

type checkinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckinServiceClient(cc grpc.ClientConnInterface) CheckinServiceClient {
	return &checkinServiceClient{cc}
}

func (c *checkinServiceClient) CreateCheckin(ctx context.Context, in *CreateCheckinRequest, opts ...grpc.CallOption) (*CreateCheckinResponse, error) {
	out := new(CreateCheckinResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CheckinService/CreateCheckin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) GetCheckin(ctx context.Context, in *GetCheckinRequest, opts ...grpc.CallOption) (*GetCheckinResponse, error) {
	out := new(GetCheckinResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CheckinService/GetCheckin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) ListRoomCheckins(ctx context.Context, in *ListRoomCheckinsRequest, opts ...grpc.CallOption) (*ListRoomCheckinsResponse, error) {
	out := new(ListRoomCheckinsResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CheckinService/ListRoomCheckins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) CastVote(ctx context.Context, in *CastVoteRequest, opts ...grpc.CallOption) (*CastVoteResponse, error) {
	out := new(CastVoteResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CheckinService/CastVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) GetCheckinPhoto(ctx context.Context, in *GetCheckinPhotoRequest, opts ...grpc.CallOption) (CheckinService_GetCheckinPhotoClient, error) {
	stream, err := c.cc.NewStream(ctx, &CheckinService_ServiceDesc.Streams[0], "/buddygym.v1.CheckinService/GetCheckinPhoto", opts...)
	if err != nil {
		return nil, err
	}
	x := &checkinServiceGetCheckinPhotoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CheckinService_GetCheckinPhotoClient interface {
	Recv() (*CheckinPhotoChunk, error)
	grpc.ClientStream
}

type checkinServiceGetCheckinPhotoClient struct {
	grpc.ClientStream
}

func (x *checkinServiceGetCheckinPhotoClient) Recv() (*CheckinPhotoChunk, error) {
	m := new(CheckinPhotoChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *checkinServiceClient) PurgeRoom(ctx context.Context, in *PurgeRoomRequest, opts ...grpc.CallOption) (*PurgeRoomResponse, error) {
	out := new(PurgeRoomResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CheckinService/PurgeRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) SyncRoomVotesRequired(ctx context.Context, in *SyncRoomVotesRequiredRequest, opts ...grpc.CallOption) (*SyncRoomVotesRequiredResponse, error) {
	out := new(SyncRoomVotesRequiredResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CheckinService/SyncRoomVotesRequired", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckinServiceServer is the server API for CheckinService service.
// All implementations must embed UnimplementedCheckinServiceServer
// for forward compatibility
type CheckinServiceServer interface {
	CreateCheckin(context.Context, *CreateCheckinRequest) (*CreateCheckinResponse, error)
	GetCheckin(context.Context, *GetCheckinRequest) (*GetCheckinResponse, error)
	ListRoomCheckins(context.Context, *ListRoomCheckinsRequest) (*ListRoomCheckinsResponse, error)
	CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error)
	// photos are never public: core streams them to authorized room members
	GetCheckinPhoto(*GetCheckinPhotoRequest, CheckinService_GetCheckinPhotoServer) error
	// core calls this when a room is gone for good
	PurgeRoom(context.Context, *PurgeRoomRequest) (*PurgeRoomResponse, error)
	// core calls this when the room's votes_required changes: pending checkins get the new
	// quorum and are re-finalized against the votes they already hold
	SyncRoomVotesRequired(context.Context, *SyncRoomVotesRequiredRequest) (*SyncRoomVotesRequiredResponse, error)
	mustEmbedUnimplementedCheckinServiceServer()
}

// UnimplementedCheckinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckinServiceServer struct {
}

func (UnimplementedCheckinServiceServer) CreateCheckin(context.Context, *CreateCheckinRequest) (*CreateCheckinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCheckin not implemented")
}
func (UnimplementedCheckinServiceServer) GetCheckin(context.Context, *GetCheckinRequest) (*GetCheckinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckin not implemented")
}
func (UnimplementedCheckinServiceServer) ListRoomCheckins(context.Context, *ListRoomCheckinsRequest) (*ListRoomCheckinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoomCheckins not implemented")
}
func (UnimplementedCheckinServiceServer) CastVote(context.Context, *CastVoteRequest) (*CastVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastVote not implemented")
}
func (UnimplementedCheckinServiceServer) GetCheckinPhoto(*GetCheckinPhotoRequest, CheckinService_GetCheckinPhotoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCheckinPhoto not implemented")
}
func (UnimplementedCheckinServiceServer) PurgeRoom(context.Context, *PurgeRoomRequest) (*PurgeRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeRoom not implemented")
}
func (UnimplementedCheckinServiceServer) SyncRoomVotesRequired(context.Context, *SyncRoomVotesRequiredRequest) (*SyncRoomVotesRequiredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncRoomVotesRequired not implemented")
}
func (UnimplementedCheckinServiceServer) mustEmbedUnimplementedCheckinServiceServer() {}

// UnsafeCheckinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckinServiceServer will
// result in compilation errors.
type UnsafeCheckinServiceServer interface {
	mustEmbedUnimplementedCheckinServiceServer()
}

func RegisterCheckinServiceServer(s grpc.ServiceRegistrar, srv CheckinServiceServer) {
	s.RegisterService(&CheckinService_ServiceDesc, srv)
}

func _CheckinService_CreateCheckin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).CreateCheckin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CheckinService/CreateCheckin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).CreateCheckin(ctx, req.(*CreateCheckinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_GetCheckin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).GetCheckin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CheckinService/GetCheckin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).GetCheckin(ctx, req.(*GetCheckinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_ListRoomCheckins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomCheckinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).ListRoomCheckins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CheckinService/ListRoomCheckins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).ListRoomCheckins(ctx, req.(*ListRoomCheckinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CheckinService/CastVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).CastVote(ctx, req.(*CastVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_GetCheckinPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCheckinPhotoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CheckinServiceServer).GetCheckinPhoto(m, &checkinServiceGetCheckinPhotoServer{stream})
}

type CheckinService_GetCheckinPhotoServer interface {
	Send(*CheckinPhotoChunk) error
	grpc.ServerStream
}

type checkinServiceGetCheckinPhotoServer struct {
	grpc.ServerStream
}

func (x *checkinServiceGetCheckinPhotoServer) Send(m *CheckinPhotoChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _CheckinService_PurgeRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).PurgeRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CheckinService/PurgeRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).PurgeRoom(ctx, req.(*PurgeRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_SyncRoomVotesRequired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRoomVotesRequiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).SyncRoomVotesRequired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CheckinService/SyncRoomVotesRequired",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).SyncRoomVotesRequired(ctx, req.(*SyncRoomVotesRequiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckinService_ServiceDesc is the grpc.ServiceDesc for CheckinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buddygym.v1.CheckinService",
	HandlerType: (*CheckinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCheckin",
			Handler:    _CheckinService_CreateCheckin_Handler,
		},
		{
			MethodName: "GetCheckin",
			Handler:    _CheckinService_GetCheckin_Handler,
		},
		{
			MethodName: "ListRoomCheckins",
			Handler:    _CheckinService_ListRoomCheckins_Handler,
		},
		{
			MethodName: "CastVote",
			Handler:    _CheckinService_CastVote_Handler,
		},
		{
			MethodName: "PurgeRoom",
			Handler:    _CheckinService_PurgeRoom_Handler,
		},
		{
			MethodName: "SyncRoomVotesRequired",
			Handler:    _CheckinService_SyncRoomVotesRequired_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCheckinPhoto",
			Handler:       _CheckinService_GetCheckinPhoto_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "buddygym/v1/checkin.proto",
}
