// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoreInternalServiceClient is the client API for CoreInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreInternalServiceClient interface {
	ApplyCheckinResult(ctx context.Context, in *ApplyCheckinResultRequest, opts ...grpc.CallOption) (*ApplyCheckinResultResponse, error)
	GetRoomVerification(ctx context.Context, in *GetRoomVerificationRequest, opts ...grpc.CallOption) (*GetRoomVerificationResponse, error)
}

type coreInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreInternalServiceClient(cc grpc.ClientConnInterface) CoreInternalServiceClient {
	return &coreInternalServiceClient{cc}
}

func (c *coreInternalServiceClient) ApplyCheckinResult(ctx context.Context, in *ApplyCheckinResultRequest, opts ...grpc.CallOption) (*ApplyCheckinResultResponse, error) {
	out := new(ApplyCheckinResultResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CoreInternalService/ApplyCheckinResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreInternalServiceClient) GetRoomVerification(ctx context.Context, in *GetRoomVerificationRequest, opts ...grpc.CallOption) (*GetRoomVerificationResponse, error) {
	out := new(GetRoomVerificationResponse)
	err := c.cc.Invoke(ctx, "/buddygym.v1.CoreInternalService/GetRoomVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreInternalServiceServer is the server API for CoreInternalService service.
// All implementations must embed UnimplementedCoreInternalServiceServer
// for forward compatibility
type CoreInternalServiceServer interface {
	ApplyCheckinResult(context.Context, *ApplyCheckinResultRequest) (*ApplyCheckinResultResponse, error)
	GetRoomVerification(context.Context, *GetRoomVerificationRequest) (*GetRoomVerificationResponse, error)
	mustEmbedUnimplementedCoreInternalServiceServer()
}

// UnimplementedCoreInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoreInternalServiceServer struct {
}

func (UnimplementedCoreInternalServiceServer) ApplyCheckinResult(context.Context, *ApplyCheckinResultRequest) (*ApplyCheckinResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyCheckinResult not implemented")
}
func (UnimplementedCoreInternalServiceServer) GetRoomVerification(context.Context, *GetRoomVerificationRequest) (*GetRoomVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomVerification not implemented")
}
func (UnimplementedCoreInternalServiceServer) mustEmbedUnimplementedCoreInternalServiceServer() {}

// UnsafeCoreInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreInternalServiceServer will
// result in compilation errors.
type UnsafeCoreInternalServiceServer interface {
	mustEmbedUnimplementedCoreInternalServiceServer()
}

func RegisterCoreInternalServiceServer(s grpc.ServiceRegistrar, srv CoreInternalServiceServer) {
	s.RegisterService(&CoreInternalService_ServiceDesc, srv)
}

func _CoreInternalService_ApplyCheckinResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCheckinResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreInternalServiceServer).ApplyCheckinResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CoreInternalService/ApplyCheckinResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreInternalServiceServer).ApplyCheckinResult(ctx, req.(*ApplyCheckinResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreInternalService_GetRoomVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreInternalServiceServer).GetRoomVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buddygym.v1.CoreInternalService/GetRoomVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreInternalServiceServer).GetRoomVerification(ctx, req.(*GetRoomVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreInternalService_ServiceDesc is the grpc.ServiceDesc for CoreInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buddygym.v1.CoreInternalService",
	HandlerType: (*CoreInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyCheckinResult",
			Handler:    _CoreInternalService_ApplyCheckinResult_Handler,
		},
		{
			MethodName: "GetRoomVerification",
			Handler:    _CoreInternalService_GetRoomVerification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buddygym/v1/core.proto",
}
