# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from buddygym.v1 import checkin_pb2 as buddygym_dot_v1_dot_checkin__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in buddygym/v1/checkin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CheckinServiceStub:
    """CheckinService is implemented by checkin-service (Python).
    core-service calls it as a proxy for the frontend.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCheckin = channel.unary_unary(
                '/buddygym.v1.CheckinService/CreateCheckin',
                request_serializer=buddygym_dot_v1_dot_checkin__pb2.CreateCheckinRequest.SerializeToString,
                response_deserializer=buddygym_dot_v1_dot_checkin__pb2.CreateCheckinResponse.FromString,
                _registered_method=True)
        self.GetCheckin = channel.unary_unary(
                '/buddygym.v1.CheckinService/GetCheckin',
                request_serializer=buddygym_dot_v1_dot_checkin__pb2.GetCheckinRequest.SerializeToString,
                response_deserializer=buddygym_dot_v1_dot_checkin__pb2.GetCheckinResponse.FromString,
                _registered_method=True)
        self.ListRoomCheckins = channel.unary_unary(
                '/buddygym.v1.CheckinService/ListRoomCheckins',
                request_serializer=buddygym_dot_v1_dot_checkin__pb2.ListRoomCheckinsRequest.SerializeToString,
                response_deserializer=buddygym_dot_v1_dot_checkin__pb2.ListRoomCheckinsResponse.FromString,
                _registered_method=True)
        self.CastVote = channel.unary_unary(
                '/buddygym.v1.CheckinService/CastVote',
                request_serializer=buddygym_dot_v1_dot_checkin__pb2.CastVoteRequest.SerializeToString,
                response_deserializer=buddygym_dot_v1_dot_checkin__pb2.CastVoteResponse.FromString,
                _registered_method=True)
        self.GetCheckinPhoto = channel.unary_stream(
                '/buddygym.v1.CheckinService/GetCheckinPhoto',
                request_serializer=buddygym_dot_v1_dot_checkin__pb2.GetCheckinPhotoRequest.SerializeToString,
                response_deserializer=buddygym_dot_v1_dot_checkin__pb2.CheckinPhotoChunk.FromString,
                _registered_method=True)
        self.PurgeRoom = channel.unary_unary(
                '/buddygym.v1.CheckinService/PurgeRoom',
                request_serializer=buddygym_dot_v1_dot_checkin__pb2.PurgeRoomRequest.SerializeToString,
                response_deserializer=buddygym_dot_v1_dot_checkin__pb2.PurgeRoomResponse.FromString,
                _registered_method=True)
        self.SyncRoomVotesRequired = channel.unary_unary(
                '/buddygym.v1.CheckinService/SyncRoomVotesRequired',
                request_serializer=buddygym_dot_v1_dot_checkin__pb2.SyncRoomVotesRequiredRequest.SerializeToString,
                response_deserializer=buddygym_dot_v1_dot_checkin__pb2.SyncRoomVotesRequiredResponse.FromString,
                _registered_method=True)


class CheckinServiceServicer:
    """CheckinService is implemented by checkin-service (Python).
    core-service calls it as a proxy for the frontend.
    """

    def CreateCheckin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoomCheckins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CastVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckinPhoto(self, request, context):
        """photos are never public: core streams them to authorized room members
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeRoom(self, request, context):
        """core calls this when a room is gone for good
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncRoomVotesRequired(self, request, context):
        """core calls this when the room's votes_required changes: pending checkins get the new
        quorum and are re-finalized against the votes they already hold
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCheckin': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckin,
                    request_deserializer=buddygym_dot_v1_dot_checkin__pb2.CreateCheckinRequest.FromString,
                    response_serializer=buddygym_dot_v1_dot_checkin__pb2.CreateCheckinResponse.SerializeToString,
            ),
            'GetCheckin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckin,
                    request_deserializer=buddygym_dot_v1_dot_checkin__pb2.GetCheckinRequest.FromString,
                    response_serializer=buddygym_dot_v1_dot_checkin__pb2.GetCheckinResponse.SerializeToString,
            ),
            'ListRoomCheckins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoomCheckins,
                    request_deserializer=buddygym_dot_v1_dot_checkin__pb2.ListRoomCheckinsRequest.FromString,
                    response_serializer=buddygym_dot_v1_dot_checkin__pb2.ListRoomCheckinsResponse.SerializeToString,
            ),
            'CastVote': grpc.unary_unary_rpc_method_handler(
                    servicer.CastVote,
                    request_deserializer=buddygym_dot_v1_dot_checkin__pb2.CastVoteRequest.FromString,
                    response_serializer=buddygym_dot_v1_dot_checkin__pb2.CastVoteResponse.SerializeToString,
            ),
            'GetCheckinPhoto': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCheckinPhoto,
                    request_deserializer=buddygym_dot_v1_dot_checkin__pb2.GetCheckinPhotoRequest.FromString,
                    response_serializer=buddygym_dot_v1_dot_checkin__pb2.CheckinPhotoChunk.SerializeToString,
            ),
            'PurgeRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeRoom,
                    request_deserializer=buddygym_dot_v1_dot_checkin__pb2.PurgeRoomRequest.FromString,
                    response_serializer=buddygym_dot_v1_dot_checkin__pb2.PurgeRoomResponse.SerializeToString,
            ),
            'SyncRoomVotesRequired': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncRoomVotesRequired,
                    request_deserializer=buddygym_dot_v1_dot_checkin__pb2.SyncRoomVotesRequiredRequest.FromString,
                    response_serializer=buddygym_dot_v1_dot_checkin__pb2.SyncRoomVotesRequiredResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buddygym.v1.CheckinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('buddygym.v1.CheckinService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckinService:
    """CheckinService is implemented by checkin-service (Python).
    core-service calls it as a proxy for the frontend.
    """

    @staticmethod
    def CreateCheckin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buddygym.v1.CheckinService/CreateCheckin',
            buddygym_dot_v1_dot_checkin__pb2.CreateCheckinRequest.SerializeToString,
            buddygym_dot_v1_dot_checkin__pb2.CreateCheckinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buddygym.v1.CheckinService/GetCheckin',
            buddygym_dot_v1_dot_checkin__pb2.GetCheckinRequest.SerializeToString,
            buddygym_dot_v1_dot_checkin__pb2.GetCheckinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoomCheckins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buddygym.v1.CheckinService/ListRoomCheckins',
            buddygym_dot_v1_dot_checkin__pb2.ListRoomCheckinsRequest.SerializeToString,
            buddygym_dot_v1_dot_checkin__pb2.ListRoomCheckinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CastVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buddygym.v1.CheckinService/CastVote',
            buddygym_dot_v1_dot_checkin__pb2.CastVoteRequest.SerializeToString,
            buddygym_dot_v1_dot_checkin__pb2.CastVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckinPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/buddygym.v1.CheckinService/GetCheckinPhoto',
            buddygym_dot_v1_dot_checkin__pb2.GetCheckinPhotoRequest.SerializeToString,
            buddygym_dot_v1_dot_checkin__pb2.CheckinPhotoChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buddygym.v1.CheckinService/PurgeRoom',
            buddygym_dot_v1_dot_checkin__pb2.PurgeRoomRequest.SerializeToString,
            buddygym_dot_v1_dot_checkin__pb2.PurgeRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncRoomVotesRequired(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buddygym.v1.CheckinService/SyncRoomVotesRequired',
            buddygym_dot_v1_dot_checkin__pb2.SyncRoomVotesRequiredRequest.SerializeToString,
            buddygym_dot_v1_dot_checkin__pb2.SyncRoomVotesRequiredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
